// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SimpleFactory
{
    public class OperationFactory
    {
        public static Operation createOpration (string operationStr)
        {
            Operation oper = null;
            switch (operationStr) {
            case "+":
                oper = new OperationAdd ();
                break;
            case "-":
                oper = new OperationSub ();
                break;
            case "*":
                oper = new OperationMul ();
                break;
            case "/":
                oper = new OperationDiv ();
                break;
            }
            return oper;
        }
    }
}

