// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SimpleFactory
{
    public class OperationDiv : Operation
    {
        public override double getResult ()
        {
            if (NumberB == 0)
                throw new Exception ("Divisor can not be 0!");
            return NumberA / NumberB;
        }
    }
}

