// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SimpleFactory
{
    public class Operation
    {
        private double _numberA = 0;
        private double _numberB = 0;

        public double NumberA {
            get { return _numberA;}
            set { _numberA = value;}
        }

        public double NumberB {
            get { return _numberB;}
            set { _numberB = value;}
        }

        public virtual double getResult ()
        {
            double result = 0;
            return result;
        }
    }

}

