// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Mediator
{
    class ConcreteColleague1 : Colleague
    {
        public ConcreteColleague1 (Mediator m) : base(m)
        {
        }
        public void Send (string message)
        {
            mediator.Send (message, this);
        }
        public void Notify (string message)
        {
            Console.WriteLine ("c1 receive message " + message);
        }
    }
}

