// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Mediator
{
    class ConcreteMediator : Mediator
    {
        private ConcreteColleague1 c1;
        public ConcreteColleague1 C1 {
            set { c1 = value;}
        }
        private ConcreteColleague2 c2;
        public ConcreteColleague2 C2 {
            set { c2 = value;}
        }

        public override void Send (string message, Colleague c)
        {
            if (c == c1)
                c2.Notify (message);
            else
                c1.Notify (message);

        }
    }
}

