// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Singleton
{
    public class SingletonClass
    {
        private static SingletonClass Instance;
        private SingletonClass ()
        {
        }

        public static SingletonClass GetInstance ()
        {
            if (Instance == null)
                Instance = new SingletonClass ();
            return Instance;
        }
    }
}

